# Generated by Django 4.1.7 on 2023-05-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_name_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
