# Generated by Django 4.1.7 on 2023-06-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_username_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
